edition = "2021"
indent_style = "Block"
use_small_heuristics = "Max"
version = "Two"

# format target
format_code_in_doc_comments = true
format_strings = true
wrap_comments = true

# Simplification
merge_derives = true
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
blank_lines_upper_bound = 1
normalize_comments = true
group_imports = "StdExternalCrate"

# Sort
reorder_imports = true
reorder_modules = true
imports_granularity="Crate"


# Indentation
enum_discrim_align_threshold = 10